version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://catcouture-g1og.onrender.com
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
      - "9229:9229"
    environment:
      - PGDATABASE=cat_couture_dpam
      - PGHOST=dpg-cjo1tqb58phs73fpp240-a
      - PGUSER=cat_couture_dpam_user
      - PGPASSWORD=U0e9OHvYYCiVicbfIVAffD2LsGH6s8tY
      - PGPORT=5432
      - SSL=false
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-volume:
